import type { CounterVoiceFailure } from "./counter-speech";

export interface CounterVoiceStrings {
  speak: string;
  connecting: string;
  listening: string;
  finishing: string;
  translating: string;
  fallback: string;
  confirmTranscript: (text: string) => string;
  yes: string;
  speakAgain: string;
  failure: (failure: CounterVoiceFailure) => string | null;
}

const createFailureCopy = (copy: {
  permission: string;
  noSpeech: string;
  unavailable: string;
  failed: string;
}) => (failure: CounterVoiceFailure): string | null => {
  if (failure === "stopped") return null;
  if (failure === "permission") return copy.permission;
  if (failure === "no-speech") return copy.noSpeech;
  if (failure === "unavailable") return copy.unavailable;
  return copy.failed;
};

const EN: CounterVoiceStrings = {
  speak: "Speak",
  connecting: "Getting ready…",
  listening: "Listening",
  finishing: "Got it",
  translating: "Translating…",
  fallback: "Voice input switched automatically. Please keep speaking.",
  confirmTranscript: (text) => `Is “${text}” correct?`,
  yes: "Yes",
  speakAgain: "Speak again",
  failure: createFailureCopy({
    permission: "The microphone is blocked. Allow access or type your message.",
    noSpeech: "Nothing was heard. Try again or type your message.",
    unavailable: "Voice input is unavailable. Please type your message.",
    failed: "Voice input stopped. Try again or type your message.",
  }),
};

const COPY: Record<string, CounterVoiceStrings> = {
  ko: {
    speak: "말하기",
    connecting: "준비 중…",
    listening: "듣고 있어요",
    finishing: "들었어요",
    translating: "번역 중…",
    fallback: "음성 연결을 자동으로 바꿨어요. 계속 말씀해 주세요.",
    confirmTranscript: (text) => `“${text}” 맞나요?`,
    yes: "맞아요",
    speakAgain: "다시 말하기",
    failure: createFailureCopy({
      permission: "마이크를 사용할 수 없습니다. 권한을 허용하거나 직접 입력해 주세요.",
      noSpeech: "아무 말도 들리지 않았어요. 다시 말하거나 직접 입력해 주세요.",
      unavailable: "이 기기에서는 음성 입력을 사용할 수 없어요. 직접 입력해 주세요.",
      failed: "음성 입력이 멈췄어요. 다시 시도하거나 직접 입력해 주세요.",
    }),
  },
  zh: {
    speak: "说话",
    connecting: "准备中…",
    listening: "正在听",
    finishing: "听到了",
    translating: "翻译中…",
    fallback: "已自动切换语音输入。请继续说话。",
    confirmTranscript: (text) => `“${text}”对吗？`,
    yes: "对",
    speakAgain: "重新说",
    failure: createFailureCopy({
      permission: "无法使用麦克风。请允许访问或直接输入。",
      noSpeech: "没有听到内容。请重试或直接输入。",
      unavailable: "此设备无法使用语音输入。请直接输入。",
      failed: "语音输入已停止。请重试或直接输入。",
    }),
  },
  ja: {
    speak: "話す",
    connecting: "準備中…",
    listening: "聞いています",
    finishing: "聞き取りました",
    translating: "翻訳中…",
    fallback: "音声入力を自動で切り替えました。そのまま話してください。",
    confirmTranscript: (text) => `「${text}」で合っていますか？`,
    yes: "はい",
    speakAgain: "もう一度話す",
    failure: createFailureCopy({
      permission: "マイクを使用できません。許可するか、直接入力してください。",
      noSpeech: "音声が聞き取れませんでした。もう一度話すか入力してください。",
      unavailable: "この端末では音声入力を使用できません。直接入力してください。",
      failed: "音声入力が停止しました。再試行するか直接入力してください。",
    }),
  },
  vi: {
    speak: "Nói",
    connecting: "Đang chuẩn bị…",
    listening: "Đang nghe",
    finishing: "Đã nghe",
    translating: "Đang dịch…",
    fallback: "Đã tự động đổi cách nhập giọng nói. Hãy tiếp tục nói.",
    confirmTranscript: (text) => `“${text}” có đúng không?`,
    yes: "Đúng",
    speakAgain: "Nói lại",
    failure: createFailureCopy({
      permission: "Không dùng được micrô. Hãy cho phép hoặc nhập bằng bàn phím.",
      noSpeech: "Không nghe thấy gì. Hãy thử lại hoặc nhập bằng bàn phím.",
      unavailable: "Thiết bị này không hỗ trợ nhập giọng nói. Hãy nhập bằng bàn phím.",
      failed: "Nhập giọng nói đã dừng. Hãy thử lại hoặc nhập bằng bàn phím.",
    }),
  },
  th: {
    speak: "พูด",
    connecting: "กำลังเตรียม…",
    listening: "กำลังฟัง",
    finishing: "ได้ยินแล้ว",
    translating: "กำลังแปล…",
    fallback: "ระบบเปลี่ยนการรับเสียงให้อัตโนมัติ กรุณาพูดต่อ",
    confirmTranscript: (text) => `“${text}” ถูกต้องไหม?`,
    yes: "ถูกต้อง",
    speakAgain: "พูดอีกครั้ง",
    failure: createFailureCopy({
      permission: "ใช้ไมโครโฟนไม่ได้ กรุณาอนุญาตหรือพิมพ์ข้อความ",
      noSpeech: "ไม่ได้ยินเสียง กรุณาลองใหม่หรือพิมพ์ข้อความ",
      unavailable: "อุปกรณ์นี้ใช้การป้อนเสียงไม่ได้ กรุณาพิมพ์ข้อความ",
      failed: "การป้อนเสียงหยุดลง กรุณาลองใหม่หรือพิมพ์ข้อความ",
    }),
  },
  id: {
    speak: "Bicara",
    connecting: "Menyiapkan…",
    listening: "Mendengarkan",
    finishing: "Sudah terdengar",
    translating: "Menerjemahkan…",
    fallback: "Input suara dialihkan otomatis. Silakan lanjut bicara.",
    confirmTranscript: (text) => `Apakah “${text}” benar?`,
    yes: "Benar",
    speakAgain: "Bicara lagi",
    failure: createFailureCopy({
      permission: "Mikrofon tidak dapat digunakan. Izinkan akses atau ketik pesan.",
      noSpeech: "Tidak ada suara yang terdengar. Coba lagi atau ketik pesan.",
      unavailable: "Input suara tidak tersedia di perangkat ini. Silakan ketik pesan.",
      failed: "Input suara berhenti. Coba lagi atau ketik pesan.",
    }),
  },
  ru: {
    speak: "Говорить",
    connecting: "Подготовка…",
    listening: "Слушаю",
    finishing: "Услышал",
    translating: "Перевод…",
    fallback: "Голосовой ввод переключён автоматически. Продолжайте говорить.",
    confirmTranscript: (text) => `Верно: «${text}»?`,
    yes: "Да",
    speakAgain: "Сказать ещё раз",
    failure: createFailureCopy({
      permission: "Микрофон недоступен. Разрешите доступ или введите текст.",
      noSpeech: "Речь не слышна. Попробуйте ещё раз или введите текст.",
      unavailable: "Голосовой ввод недоступен на этом устройстве. Введите текст.",
      failed: "Голосовой ввод остановлен. Попробуйте снова или введите текст.",
    }),
  },
  uz: {
    speak: "Gapirish",
    connecting: "Tayyorlanmoqda…",
    listening: "Tinglayapman",
    finishing: "Eshitildi",
    translating: "Tarjima qilinmoqda…",
    fallback: "Ovozli kiritish avtomatik almashtirildi. Gapirishda davom eting.",
    confirmTranscript: (text) => `“${text}” toʻgʻrimi?`,
    yes: "Ha",
    speakAgain: "Qayta gapirish",
    failure: createFailureCopy({
      permission: "Mikrofondan foydalanib bo‘lmaydi. Ruxsat bering yoki matn kiriting.",
      noSpeech: "Hech narsa eshitilmadi. Qayta urinib ko‘ring yoki matn kiriting.",
      unavailable: "Bu qurilmada ovozli kiritish mavjud emas. Matn kiriting.",
      failed: "Ovozli kiritish to‘xtadi. Qayta urinib ko‘ring yoki matn kiriting.",
    }),
  },
  mn: {
    speak: "Ярих",
    connecting: "Бэлтгэж байна…",
    listening: "Сонсож байна",
    finishing: "Сонссон",
    translating: "Орчуулж байна…",
    fallback: "Дуу хоолойн оролтыг автоматаар сольлоо. Үргэлжлүүлэн ярина уу.",
    confirmTranscript: (text) => `“${text}” зөв үү?`,
    yes: "Тийм",
    speakAgain: "Дахин ярих",
    failure: createFailureCopy({
      permission: "Микрофон ашиглах боломжгүй. Зөвшөөрөх эсвэл текстээр оруулна уу.",
      noSpeech: "Юу ч сонсогдсонгүй. Дахин оролдох эсвэл текстээр оруулна уу.",
      unavailable: "Энэ төхөөрөмж дээр дуу хоолойн оролт ашиглах боломжгүй. Текстээр оруулна уу.",
      failed: "Дуу хоолойн оролт зогслоо. Дахин оролдох эсвэл текстээр оруулна уу.",
    }),
  },
  ne: {
    speak: "बोल्नुहोस्",
    connecting: "तयार हुँदैछ…",
    listening: "सुनिरहेको छु",
    finishing: "सुनेँ",
    translating: "अनुवाद हुँदैछ…",
    fallback: "आवाज इनपुट स्वतः परिवर्तन भयो। बोलिरहनुहोस्।",
    confirmTranscript: (text) => `“${text}” सही हो?`,
    yes: "हो",
    speakAgain: "फेरि बोल्नुहोस्",
    failure: createFailureCopy({
      permission: "माइक्रोफोन प्रयोग गर्न सकिँदैन। अनुमति दिनुहोस् वा सन्देश टाइप गर्नुहोस्।",
      noSpeech: "केही सुनिएन। फेरि प्रयास गर्नुहोस् वा सन्देश टाइप गर्नुहोस्।",
      unavailable: "यो उपकरणमा आवाज इनपुट उपलब्ध छैन। सन्देश टाइप गर्नुहोस्।",
      failed: "आवाज इनपुट रोकियो। फेरि प्रयास गर्नुहोस् वा सन्देश टाइप गर्नुहोस्।",
    }),
  },
  km: {
    speak: "និយាយ",
    connecting: "កំពុងរៀបចំ…",
    listening: "កំពុងស្តាប់",
    finishing: "បានឮហើយ",
    translating: "កំពុងបកប្រែ…",
    fallback: "ប្រព័ន្ធបានប្តូរការបញ្ចូលសំឡេងដោយស្វ័យប្រវត្តិ។ សូមបន្តនិយាយ។",
    confirmTranscript: (text) => `“${text}” ត្រឹមត្រូវទេ?`,
    yes: "ត្រឹមត្រូវ",
    speakAgain: "និយាយម្តងទៀត",
    failure: createFailureCopy({
      permission: "មិនអាចប្រើមីក្រូហ្វូនបានទេ។ សូមអនុញ្ញាត ឬវាយសារ។",
      noSpeech: "មិនបានឮអ្វីទេ។ សូមសាកម្តងទៀត ឬវាយសារ។",
      unavailable: "ឧបករណ៍នេះមិនអាចប្រើការបញ្ចូលសំឡេងបានទេ។ សូមវាយសារ។",
      failed: "ការបញ្ចូលសំឡេងបានឈប់។ សូមសាកម្តងទៀត ឬវាយសារ។",
    }),
  },
  my: {
    speak: "ပြောရန်",
    connecting: "ပြင်ဆင်နေသည်…",
    listening: "နားထောင်နေသည်",
    finishing: "ကြားပြီးပါပြီ",
    translating: "ဘာသာပြန်နေသည်…",
    fallback: "အသံထည့်သွင်းမှုကို အလိုအလျောက် ပြောင်းထားသည်။ ဆက်ပြောပါ။",
    confirmTranscript: (text) => `“${text}” မှန်ပါသလား?`,
    yes: "မှန်ပါတယ်",
    speakAgain: "ထပ်ပြောရန်",
    failure: createFailureCopy({
      permission: "မိုက်ခရိုဖုန်းကို အသုံးမပြုနိုင်ပါ။ ခွင့်ပြုပါ သို့မဟုတ် စာရိုက်ပါ။",
      noSpeech: "ဘာမှ မကြားရပါ။ ထပ်စမ်းပါ သို့မဟုတ် စာရိုက်ပါ။",
      unavailable: "ဤစက်တွင် အသံထည့်သွင်းမှု မရနိုင်ပါ။ စာရိုက်ပါ။",
      failed: "အသံထည့်သွင်းမှု ရပ်သွားသည်။ ထပ်စမ်းပါ သို့မဟုတ် စာရိုက်ပါ။",
    }),
  },
  tl: {
    speak: "Magsalita",
    connecting: "Naghahanda…",
    listening: "Nakikinig",
    finishing: "Narinig na",
    translating: "Nagsasalin…",
    fallback: "Awtomatikong pinalitan ang voice input. Magpatuloy sa pagsasalita.",
    confirmTranscript: (text) => `Tama ba ang “${text}”?`,
    yes: "Oo",
    speakAgain: "Magsalita ulit",
    failure: createFailureCopy({
      permission: "Hindi magamit ang mikropono. Payagan ang access o i-type ang mensahe.",
      noSpeech: "Walang narinig. Subukan ulit o i-type ang mensahe.",
      unavailable: "Hindi available ang voice input sa device na ito. I-type ang mensahe.",
      failed: "Huminto ang voice input. Subukan ulit o i-type ang mensahe.",
    }),
  },
  es: {
    speak: "Hablar",
    connecting: "Preparando…",
    listening: "Escuchando",
    finishing: "Entendido",
    translating: "Traduciendo…",
    fallback: "La entrada por voz cambió automáticamente. Siga hablando.",
    confirmTranscript: (text) => `¿Es correcto “${text}”?`,
    yes: "Sí",
    speakAgain: "Hablar de nuevo",
    failure: createFailureCopy({
      permission: "No se puede usar el micrófono. Permita el acceso o escriba su mensaje.",
      noSpeech: "No se oyó nada. Inténtelo de nuevo o escriba su mensaje.",
      unavailable: "La entrada por voz no está disponible en este dispositivo. Escriba su mensaje.",
      failed: "La entrada por voz se detuvo. Inténtelo de nuevo o escriba su mensaje.",
    }),
  },
  fr: {
    speak: "Parler",
    connecting: "Préparation…",
    listening: "J’écoute",
    finishing: "Compris",
    translating: "Traduction…",
    fallback: "La saisie vocale a été changée automatiquement. Continuez à parler.",
    confirmTranscript: (text) => `« ${text} » est correct ?`,
    yes: "Oui",
    speakAgain: "Parler à nouveau",
    failure: createFailureCopy({
      permission: "Le micro est inaccessible. Autorisez l’accès ou saisissez votre message.",
      noSpeech: "Aucun son n’a été entendu. Réessayez ou saisissez votre message.",
      unavailable: "La saisie vocale n’est pas disponible sur cet appareil. Saisissez votre message.",
      failed: "La saisie vocale s’est arrêtée. Réessayez ou saisissez votre message.",
    }),
  },
  de: {
    speak: "Sprechen",
    connecting: "Wird vorbereitet…",
    listening: "Höre zu",
    finishing: "Verstanden",
    translating: "Wird übersetzt…",
    fallback: "Die Spracheingabe wurde automatisch gewechselt. Bitte weitersprechen.",
    confirmTranscript: (text) => `Ist „${text}“ richtig?`,
    yes: "Ja",
    speakAgain: "Noch einmal sprechen",
    failure: createFailureCopy({
      permission: "Das Mikrofon kann nicht verwendet werden. Erlaube den Zugriff oder gib den Text ein.",
      noSpeech: "Es wurde nichts gehört. Versuche es erneut oder gib den Text ein.",
      unavailable: "Spracheingabe ist auf diesem Gerät nicht verfügbar. Gib den Text ein.",
      failed: "Die Spracheingabe wurde beendet. Versuche es erneut oder gib den Text ein.",
    }),
  },
  pt: {
    speak: "Falar",
    connecting: "Preparando…",
    listening: "Ouvindo",
    finishing: "Entendido",
    translating: "Traduzindo…",
    fallback: "A entrada por voz foi alterada automaticamente. Continue falando.",
    confirmTranscript: (text) => `“${text}” está correto?`,
    yes: "Sim",
    speakAgain: "Falar novamente",
    failure: createFailureCopy({
      permission: "Não é possível usar o microfone. Permita o acesso ou digite sua mensagem.",
      noSpeech: "Nada foi ouvido. Tente novamente ou digite sua mensagem.",
      unavailable: "A entrada por voz não está disponível neste dispositivo. Digite sua mensagem.",
      failed: "A entrada por voz parou. Tente novamente ou digite sua mensagem.",
    }),
  },
  ar: {
    speak: "تحدّث",
    connecting: "جارٍ الاستعداد…",
    listening: "أستمع إليك",
    finishing: "تم السماع",
    translating: "جارٍ الترجمة…",
    fallback: "تم تبديل الإدخال الصوتي تلقائياً. تابع التحدث.",
    confirmTranscript: (text) => `هل «${text}» صحيح؟`,
    yes: "نعم",
    speakAgain: "التحدث مرة أخرى",
    failure: createFailureCopy({
      permission: "لا يمكن استخدام الميكروفون. اسمح بالوصول أو اكتب رسالتك.",
      noSpeech: "لم يُسمع شيء. حاول مرة أخرى أو اكتب رسالتك.",
      unavailable: "الإدخال الصوتي غير متاح على هذا الجهاز. اكتب رسالتك.",
      failed: "توقف الإدخال الصوتي. حاول مرة أخرى أو اكتب رسالتك.",
    }),
  },
  hi: {
    speak: "बोलें",
    connecting: "तैयार हो रहा है…",
    listening: "सुन रहा हूँ",
    finishing: "सुन लिया",
    translating: "अनुवाद हो रहा है…",
    fallback: "वॉइस इनपुट अपने आप बदल दिया गया है। बोलते रहें।",
    confirmTranscript: (text) => `क्या “${text}” सही है?`,
    yes: "हाँ",
    speakAgain: "फिर से बोलें",
    failure: createFailureCopy({
      permission: "माइक्रोफ़ोन इस्तेमाल नहीं किया जा सकता। अनुमति दें या संदेश टाइप करें।",
      noSpeech: "कुछ सुनाई नहीं दिया। फिर कोशिश करें या संदेश टाइप करें।",
      unavailable: "इस डिवाइस पर वॉइस इनपुट उपलब्ध नहीं है। संदेश टाइप करें।",
      failed: "वॉइस इनपुट रुक गया। फिर कोशिश करें या संदेश टाइप करें।",
    }),
  },
  bn: {
    speak: "বলুন",
    connecting: "প্রস্তুত হচ্ছে…",
    listening: "শুনছি",
    finishing: "শোনা হয়েছে",
    translating: "অনুবাদ হচ্ছে…",
    fallback: "ভয়েস ইনপুট স্বয়ংক্রিয়ভাবে পরিবর্তন হয়েছে। কথা বলতে থাকুন।",
    confirmTranscript: (text) => `“${text}” কি সঠিক?`,
    yes: "হ্যাঁ",
    speakAgain: "আবার বলুন",
    failure: createFailureCopy({
      permission: "মাইক্রোফোন ব্যবহার করা যাচ্ছে না। অনুমতি দিন বা বার্তা টাইপ করুন।",
      noSpeech: "কিছু শোনা যায়নি। আবার চেষ্টা করুন বা বার্তা টাইপ করুন।",
      unavailable: "এই ডিভাইসে ভয়েস ইনপুট পাওয়া যাচ্ছে না। বার্তা টাইপ করুন।",
      failed: "ভয়েস ইনপুট বন্ধ হয়েছে। আবার চেষ্টা করুন বা বার্তা টাইপ করুন।",
    }),
  },
  ur: {
    speak: "بولیں",
    connecting: "تیار ہو رہا ہے…",
    listening: "سن رہا ہوں",
    finishing: "سن لیا",
    translating: "ترجمہ ہو رہا ہے…",
    fallback: "وائس اِن پٹ خودکار طور پر تبدیل ہو گیا ہے۔ بولتے رہیں۔",
    confirmTranscript: (text) => `کیا “${text}” درست ہے؟`,
    yes: "ہاں",
    speakAgain: "دوبارہ بولیں",
    failure: createFailureCopy({
      permission: "مائیکروفون استعمال نہیں ہو سکتا۔ اجازت دیں یا پیغام ٹائپ کریں۔",
      noSpeech: "کچھ سنائی نہیں دیا۔ دوبارہ کوشش کریں یا پیغام ٹائپ کریں۔",
      unavailable: "اس ڈیوائس پر وائس اِن پٹ دستیاب نہیں۔ پیغام ٹائپ کریں۔",
      failed: "وائس اِن پٹ رک گیا۔ دوبارہ کوشش کریں یا پیغام ٹائپ کریں۔",
    }),
  },
  tr: {
    speak: "Konuş",
    connecting: "Hazırlanıyor…",
    listening: "Dinliyorum",
    finishing: "Duydum",
    translating: "Çevriliyor…",
    fallback: "Sesli giriş otomatik olarak değiştirildi. Konuşmaya devam edin.",
    confirmTranscript: (text) => `“${text}” doğru mu?`,
    yes: "Evet",
    speakAgain: "Tekrar konuş",
    failure: createFailureCopy({
      permission: "Mikrofon kullanılamıyor. Erişime izin verin veya mesajınızı yazın.",
      noSpeech: "Hiçbir şey duyulmadı. Tekrar deneyin veya mesajınızı yazın.",
      unavailable: "Bu cihazda sesli giriş kullanılamıyor. Mesajınızı yazın.",
      failed: "Sesli giriş durdu. Tekrar deneyin veya mesajınızı yazın.",
    }),
  },
};

export function voiceStringsFor(language: string): CounterVoiceStrings {
  return COPY[language.split("-")[0].toLowerCase()] ?? EN;
}
