/**
 * Interface strings for the counter, in the visitor's own language.
 *
 * The visitor side of Counter Mode is used by someone who, by definition, does
 * not read the staff member's language. Translating the messages but leaving
 * the buttons in Korean would put the one part they cannot ask about — how to
 * work the thing — in a script they cannot read.
 *
 * Deliberately small. Every key here is a control the visitor has to operate or
 * a state they have to understand; nothing decorative is translated, because an
 * unmaintained half-translation reads worse than English.
 *
 * Languages without an entry fall back to English rather than to Korean: a
 * visitor at a Korean counter is far more likely to manage some English than
 * some Korean, and the language picker itself is always in endonyms.
 */
export interface CounterStrings {
  pickLanguage: string;
  pickLanguageHint: string;
  start: string;
  connecting: string;
  waitingStaff: string;
  ended: string;
  typeHere: string;
  send: string;
  holdToSpeak: string;
  listening: string;
  quickPhrases: string;
  confirmNumbers: string;
  rephrase: string;
  fixedPhrase: string;
  checkThis: string;
  translationFailed: string;
  emptyConversation: string;
  changeLanguage: string;
  /** Both carry a `{provider}` placeholder, filled in by the caller. */
  sentTo: string;
  mayTrain: string;
}

const EN: CounterStrings = {
  pickLanguage: "Choose your language",
  pickLanguageHint: "Everything you write is translated for the staff member.",
  start: "Start",
  connecting: "Connecting…",
  waitingStaff: "Waiting for the staff member.",
  ended: "This conversation has ended.",
  typeHere: "Type your message",
  send: "Send",
  holdToSpeak: "Hold to speak",
  listening: "Listening…",
  quickPhrases: "Common phrases",
  confirmNumbers: "Confirm the numbers",
  rephrase: "Say it differently",
  fixedPhrase: "Set phrase",
  checkThis: "Please check",
  translationFailed: "Could not translate",
  emptyConversation: "Messages will appear here. Speak or type to begin.",
  changeLanguage: "Change language",
  sentTo: "Translated by {provider}.",
  mayTrain: "On this free tier, {provider} may use what is sent to improve their products.",
};

const STRINGS: Record<string, CounterStrings> = {
  "en-US": EN,
  "ko-KR": {
    pickLanguage: "언어를 선택하세요",
    pickLanguageHint: "작성하신 내용은 담당 직원에게 번역되어 전달됩니다.",
    start: "시작",
    connecting: "연결 중…",
    waitingStaff: "담당 직원을 기다리는 중입니다.",
    ended: "대화가 종료되었습니다.",
    typeHere: "내용을 입력하세요",
    send: "보내기",
    holdToSpeak: "길게 눌러 말하기",
    listening: "듣는 중…",
    quickPhrases: "자주 쓰는 문구",
    confirmNumbers: "숫자 확인",
    rephrase: "다시 표현",
    fixedPhrase: "정형 문구",
    checkThis: "확인 필요",
    translationFailed: "번역하지 못했습니다",
    emptyConversation: "대화가 여기에 표시됩니다. 말하거나 입력해 시작하세요.",
    changeLanguage: "언어 변경",
    sentTo: "번역은 {provider}에서 처리합니다.",
    mayTrain: "무료 등급에서는 {provider}이(가) 전송된 내용을 서비스 개선에 사용할 수 있습니다.",
  },
  "zh-CN": {
    pickLanguage: "请选择您的语言",
    pickLanguageHint: "您输入的内容会翻译后转达给工作人员。",
    start: "开始",
    connecting: "连接中…",
    waitingStaff: "正在等待工作人员。",
    ended: "对话已结束。",
    typeHere: "请输入内容",
    send: "发送",
    holdToSpeak: "按住说话",
    listening: "正在聆听…",
    quickPhrases: "常用语句",
    confirmNumbers: "确认数字",
    rephrase: "换个说法",
    fixedPhrase: "固定语句",
    checkThis: "请确认",
    translationFailed: "无法翻译",
    emptyConversation: "消息将显示在这里。说话或输入即可开始。",
    changeLanguage: "更改语言",
    sentTo: "由 {provider} 提供翻译。",
    mayTrain: "在免费方案下，{provider} 可能会使用所发送的内容来改进其产品。",
  },
  "zh-TW": {
    pickLanguage: "請選擇您的語言",
    pickLanguageHint: "您輸入的內容會翻譯後轉達給工作人員。",
    start: "開始",
    connecting: "連線中…",
    waitingStaff: "正在等待工作人員。",
    ended: "對話已結束。",
    typeHere: "請輸入內容",
    send: "傳送",
    holdToSpeak: "按住說話",
    listening: "聆聽中…",
    quickPhrases: "常用語句",
    confirmNumbers: "確認數字",
    rephrase: "換個說法",
    fixedPhrase: "固定語句",
    checkThis: "請確認",
    translationFailed: "無法翻譯",
    emptyConversation: "訊息將顯示在這裡。說話或輸入即可開始。",
    changeLanguage: "變更語言",
    sentTo: "由 {provider} 提供翻譯。",
    mayTrain: "在免費方案下，{provider} 可能會使用所傳送的內容來改進其產品。",
  },
  "ja-JP": {
    pickLanguage: "言語を選択してください",
    pickLanguageHint: "入力した内容は翻訳されて担当者に伝わります。",
    start: "開始",
    connecting: "接続中…",
    waitingStaff: "担当者をお待ちください。",
    ended: "この会話は終了しました。",
    typeHere: "メッセージを入力",
    send: "送信",
    holdToSpeak: "長押しで話す",
    listening: "聞き取り中…",
    quickPhrases: "よく使う表現",
    confirmNumbers: "数字を確認",
    rephrase: "言い換える",
    fixedPhrase: "定型文",
    checkThis: "要確認",
    translationFailed: "翻訳できませんでした",
    emptyConversation: "メッセージがここに表示されます。話すか入力して始めてください。",
    changeLanguage: "言語を変更",
    sentTo: "翻訳は {provider} が行います。",
    mayTrain: "無料枠では、{provider} が送信内容を製品改善に利用する場合があります。",
  },
  "vi-VN": {
    pickLanguage: "Chọn ngôn ngữ của bạn",
    pickLanguageHint: "Nội dung bạn viết sẽ được dịch cho nhân viên.",
    start: "Bắt đầu",
    connecting: "Đang kết nối…",
    waitingStaff: "Đang chờ nhân viên.",
    ended: "Cuộc trò chuyện đã kết thúc.",
    typeHere: "Nhập nội dung",
    send: "Gửi",
    holdToSpeak: "Giữ để nói",
    listening: "Đang nghe…",
    quickPhrases: "Câu thường dùng",
    confirmNumbers: "Xác nhận số liệu",
    rephrase: "Diễn đạt cách khác",
    fixedPhrase: "Câu mẫu",
    checkThis: "Cần kiểm tra",
    translationFailed: "Không dịch được",
    emptyConversation: "Tin nhắn sẽ hiện ở đây. Hãy nói hoặc nhập để bắt đầu.",
    changeLanguage: "Đổi ngôn ngữ",
    sentTo: "Bản dịch do {provider} thực hiện.",
    mayTrain: "Ở gói miễn phí, {provider} có thể dùng nội dung đã gửi để cải thiện sản phẩm.",
  },
  "th-TH": {
    pickLanguage: "เลือกภาษาของคุณ",
    pickLanguageHint: "ข้อความที่คุณพิมพ์จะถูกแปลให้เจ้าหน้าที่",
    start: "เริ่ม",
    connecting: "กำลังเชื่อมต่อ…",
    waitingStaff: "กำลังรอเจ้าหน้าที่",
    ended: "การสนทนาสิ้นสุดแล้ว",
    typeHere: "พิมพ์ข้อความ",
    send: "ส่ง",
    holdToSpeak: "กดค้างเพื่อพูด",
    listening: "กำลังฟัง…",
    quickPhrases: "ประโยคที่ใช้บ่อย",
    confirmNumbers: "ยืนยันตัวเลข",
    rephrase: "พูดใหม่อีกแบบ",
    fixedPhrase: "ประโยคสำเร็จรูป",
    checkThis: "โปรดตรวจสอบ",
    translationFailed: "แปลไม่สำเร็จ",
    emptyConversation: "ข้อความจะแสดงที่นี่ พูดหรือพิมพ์เพื่อเริ่ม",
    changeLanguage: "เปลี่ยนภาษา",
    sentTo: "แปลโดย {provider}",
    mayTrain: "ในแพ็กเกจฟรี {provider} อาจนำข้อความที่ส่งไปใช้เพื่อปรับปรุงผลิตภัณฑ์",
  },
  "id-ID": {
    pickLanguage: "Pilih bahasa Anda",
    pickLanguageHint: "Yang Anda tulis akan diterjemahkan untuk petugas.",
    start: "Mulai",
    connecting: "Menghubungkan…",
    waitingStaff: "Menunggu petugas.",
    ended: "Percakapan ini telah berakhir.",
    typeHere: "Ketik pesan Anda",
    send: "Kirim",
    holdToSpeak: "Tahan untuk bicara",
    listening: "Mendengarkan…",
    quickPhrases: "Kalimat umum",
    confirmNumbers: "Konfirmasi angka",
    rephrase: "Ucapkan dengan cara lain",
    fixedPhrase: "Kalimat baku",
    checkThis: "Mohon diperiksa",
    translationFailed: "Tidak dapat menerjemahkan",
    emptyConversation: "Pesan akan muncul di sini. Bicara atau ketik untuk mulai.",
    changeLanguage: "Ganti bahasa",
    sentTo: "Diterjemahkan oleh {provider}.",
    mayTrain: "Pada paket gratis, {provider} dapat memakai isi yang dikirim untuk meningkatkan produknya.",
  },
  "ru-RU": {
    pickLanguage: "Выберите ваш язык",
    pickLanguageHint: "Всё, что вы напишете, будет переведено для сотрудника.",
    start: "Начать",
    connecting: "Подключение…",
    waitingStaff: "Ожидание сотрудника.",
    ended: "Разговор завершён.",
    typeHere: "Введите сообщение",
    send: "Отправить",
    holdToSpeak: "Удерживайте, чтобы говорить",
    listening: "Слушаю…",
    quickPhrases: "Частые фразы",
    confirmNumbers: "Подтвердить цифры",
    rephrase: "Сказать иначе",
    fixedPhrase: "Готовая фраза",
    checkThis: "Проверьте",
    translationFailed: "Не удалось перевести",
    emptyConversation: "Сообщения появятся здесь. Говорите или пишите, чтобы начать.",
    changeLanguage: "Сменить язык",
    sentTo: "Перевод выполняет {provider}.",
    mayTrain: "На бесплатном тарифе {provider} может использовать отправленное для улучшения своих продуктов.",
  },
  "uz-UZ": {
    pickLanguage: "Tilingizni tanlang",
    pickLanguageHint: "Yozganlaringiz xodim uchun tarjima qilinadi.",
    start: "Boshlash",
    connecting: "Ulanmoqda…",
    waitingStaff: "Xodim kutilmoqda.",
    ended: "Suhbat tugadi.",
    typeHere: "Xabaringizni yozing",
    send: "Yuborish",
    holdToSpeak: "Gapirish uchun bosib turing",
    listening: "Tinglanmoqda…",
    quickPhrases: "Ko‘p ishlatiladigan iboralar",
    confirmNumbers: "Raqamlarni tasdiqlang",
    rephrase: "Boshqacha ayting",
    fixedPhrase: "Tayyor ibora",
    checkThis: "Tekshiring",
    translationFailed: "Tarjima qilinmadi",
    emptyConversation: "Xabarlar shu yerda ko‘rinadi. Gapiring yoki yozing.",
    changeLanguage: "Tilni o‘zgartirish",
    sentTo: "Tarjimani {provider} bajaradi.",
    mayTrain: "Bepul tarifda {provider} yuborilgan matndan mahsulotlarini yaxshilash uchun foydalanishi mumkin.",
  },
  "mn-MN": {
    pickLanguage: "Хэлээ сонгоно уу",
    pickLanguageHint: "Таны бичсэн зүйл ажилтанд орчуулагдан очно.",
    start: "Эхлэх",
    connecting: "Холбогдож байна…",
    waitingStaff: "Ажилтныг хүлээж байна.",
    ended: "Яриа дууслаа.",
    typeHere: "Мессежээ бичнэ үү",
    send: "Илгээх",
    holdToSpeak: "Дарж хэлнэ үү",
    listening: "Сонсож байна…",
    quickPhrases: "Түгээмэл хэллэг",
    confirmNumbers: "Тоог баталгаажуулах",
    rephrase: "Өөрөөр хэлэх",
    fixedPhrase: "Бэлэн хэллэг",
    checkThis: "Шалгана уу",
    translationFailed: "Орчуулж чадсангүй",
    emptyConversation: "Мессеж энд харагдана. Ярих эсвэл бичиж эхлээрэй.",
    changeLanguage: "Хэл солих",
    sentTo: "Орчуулгыг {provider} гүйцэтгэнэ.",
    mayTrain: "Үнэгүй багцад {provider} илгээсэн агуулгыг бүтээгдэхүүнээ сайжруулахад ашиглаж болно.",
  },
  "ne-NP": {
    pickLanguage: "आफ्नो भाषा छान्नुहोस्",
    pickLanguageHint: "तपाईंले लेखेको कुरा कर्मचारीका लागि अनुवाद हुन्छ।",
    start: "सुरु",
    connecting: "जडान हुँदै…",
    waitingStaff: "कर्मचारीको प्रतीक्षा गर्दै।",
    ended: "यो कुराकानी समाप्त भयो।",
    typeHere: "आफ्नो सन्देश लेख्नुहोस्",
    send: "पठाउनुहोस्",
    holdToSpeak: "बोल्न थिचिराख्नुहोस्",
    listening: "सुन्दै…",
    quickPhrases: "प्रायः प्रयोग हुने वाक्य",
    confirmNumbers: "अङ्क पुष्टि गर्नुहोस्",
    rephrase: "अर्को तरिकाले भन्नुहोस्",
    fixedPhrase: "तयारी वाक्य",
    checkThis: "जाँच्नुहोस्",
    translationFailed: "अनुवाद गर्न सकिएन",
    emptyConversation: "सन्देशहरू यहाँ देखिनेछन्। बोल्नुहोस् वा लेख्नुहोस्।",
    changeLanguage: "भाषा बदल्नुहोस्",
    sentTo: "अनुवाद {provider} ले गर्छ।",
    mayTrain: "निःशुल्क योजनामा {provider} ले पठाइएको सामग्री आफ्ना उत्पादन सुधार गर्न प्रयोग गर्न सक्छ।",
  },
  "es-ES": {
    pickLanguage: "Elija su idioma",
    pickLanguageHint: "Todo lo que escriba se traduce para el personal.",
    start: "Empezar",
    connecting: "Conectando…",
    waitingStaff: "Esperando al personal.",
    ended: "Esta conversación ha terminado.",
    typeHere: "Escriba su mensaje",
    send: "Enviar",
    holdToSpeak: "Mantenga pulsado para hablar",
    listening: "Escuchando…",
    quickPhrases: "Frases habituales",
    confirmNumbers: "Confirmar las cifras",
    rephrase: "Decirlo de otra forma",
    fixedPhrase: "Frase fija",
    checkThis: "Compruébelo",
    translationFailed: "No se pudo traducir",
    emptyConversation: "Los mensajes aparecerán aquí. Hable o escriba para empezar.",
    changeLanguage: "Cambiar de idioma",
    sentTo: "Traducido por {provider}.",
    mayTrain: "En el plan gratuito, {provider} puede usar lo enviado para mejorar sus productos.",
  },
  "fr-FR": {
    pickLanguage: "Choisissez votre langue",
    pickLanguageHint: "Ce que vous écrivez est traduit pour l’agent.",
    start: "Commencer",
    connecting: "Connexion…",
    waitingStaff: "En attente de l’agent.",
    ended: "Cette conversation est terminée.",
    typeHere: "Saisissez votre message",
    send: "Envoyer",
    holdToSpeak: "Maintenez pour parler",
    listening: "Écoute…",
    quickPhrases: "Phrases courantes",
    confirmNumbers: "Confirmer les chiffres",
    rephrase: "Dire autrement",
    fixedPhrase: "Phrase type",
    checkThis: "À vérifier",
    translationFailed: "Traduction impossible",
    emptyConversation: "Les messages s’afficheront ici. Parlez ou écrivez pour commencer.",
    changeLanguage: "Changer de langue",
    sentTo: "Traduction assurée par {provider}.",
    mayTrain: "Dans l’offre gratuite, {provider} peut utiliser ce qui est envoyé pour améliorer ses produits.",
  },
  "ar-SA": {
    pickLanguage: "اختر لغتك",
    pickLanguageHint: "كل ما تكتبه يُترجم للموظف.",
    start: "ابدأ",
    connecting: "جارٍ الاتصال…",
    waitingStaff: "في انتظار الموظف.",
    ended: "انتهت هذه المحادثة.",
    typeHere: "اكتب رسالتك",
    send: "إرسال",
    holdToSpeak: "اضغط مع الاستمرار للتحدث",
    listening: "يستمع…",
    quickPhrases: "عبارات شائعة",
    confirmNumbers: "تأكيد الأرقام",
    rephrase: "قلها بطريقة أخرى",
    fixedPhrase: "عبارة جاهزة",
    checkThis: "يرجى التحقق",
    translationFailed: "تعذّرت الترجمة",
    emptyConversation: "ستظهر الرسائل هنا. تحدّث أو اكتب للبدء.",
    changeLanguage: "تغيير اللغة",
    sentTo: "الترجمة عبر {provider}.",
    mayTrain: "في الباقة المجانية، قد يستخدم {provider} ما يُرسل لتحسين منتجاته.",
  },
  "hi-IN": {
    pickLanguage: "अपनी भाषा चुनें",
    pickLanguageHint: "आप जो लिखेंगे वह कर्मचारी के लिए अनुवादित होगा।",
    start: "शुरू करें",
    connecting: "जुड़ रहा है…",
    waitingStaff: "कर्मचारी की प्रतीक्षा है।",
    ended: "यह बातचीत समाप्त हो गई।",
    typeHere: "अपना संदेश लिखें",
    send: "भेजें",
    holdToSpeak: "बोलने के लिए दबाए रखें",
    listening: "सुन रहा है…",
    quickPhrases: "आम वाक्य",
    confirmNumbers: "अंक सत्यापित करें",
    rephrase: "दूसरे ढंग से कहें",
    fixedPhrase: "तयशुदा वाक्य",
    checkThis: "जाँच लें",
    translationFailed: "अनुवाद नहीं हो सका",
    emptyConversation: "संदेश यहाँ दिखेंगे। बोलें या लिखें।",
    changeLanguage: "भाषा बदलें",
    sentTo: "अनुवाद {provider} द्वारा।",
    mayTrain: "निःशुल्क योजना में {provider} भेजी गई सामग्री का उपयोग अपने उत्पाद सुधारने के लिए कर सकता है।",
  },
  "tr-TR": {
    pickLanguage: "Dilinizi seçin",
    pickLanguageHint: "Yazdığınız her şey görevli için çevrilir.",
    start: "Başla",
    connecting: "Bağlanıyor…",
    waitingStaff: "Görevli bekleniyor.",
    ended: "Bu görüşme sona erdi.",
    typeHere: "Mesajınızı yazın",
    send: "Gönder",
    holdToSpeak: "Konuşmak için basılı tutun",
    listening: "Dinliyor…",
    quickPhrases: "Sık kullanılan ifadeler",
    confirmNumbers: "Sayıları doğrula",
    rephrase: "Başka türlü söyle",
    fixedPhrase: "Hazır ifade",
    checkThis: "Lütfen kontrol edin",
    translationFailed: "Çevrilemedi",
    emptyConversation: "Mesajlar burada görünecek. Konuşun ya da yazın.",
    changeLanguage: "Dili değiştir",
    sentTo: "Çeviriyi {provider} yapıyor.",
    mayTrain: "Ücretsiz pakette {provider}, gönderilenleri ürünlerini geliştirmek için kullanabilir.",
  },
};

/** Strings for a language tag, falling back to the base tag and then English. */
export function stringsFor(code: string): CounterStrings {
  const exact = STRINGS[code];
  if (exact) return exact;
  const base = code.split("-")[0].toLowerCase();
  for (const [key, value] of Object.entries(STRINGS)) {
    if (key.split("-")[0].toLowerCase() === base) return value;
  }
  return EN;
}

/** Share of the interface a visitor sees in their own language. Diagnostics. */
export const hasStrings = (code: string): boolean =>
  Object.keys(STRINGS).some(
    (key) => key === code || key.split("-")[0] === code.split("-")[0].toLowerCase(),
  );
