/**
 * Interface strings for the counter, in the visitor's own language.
 *
 * The visitor side of Counter Mode is used by someone who, by definition, does
 * not read the staff member's language. Translating the messages but leaving
 * the buttons in Korean would put the one part they cannot ask about — how to
 * work the thing — in a script they cannot read.
 *
 * Deliberately small. Every key here is a control the visitor has to operate or
 * a state they have to understand; nothing decorative is translated, because an
 * unmaintained half-translation reads worse than English.
 *
 * Languages without an entry fall back to English rather than to Korean: a
 * visitor at a Korean counter is far more likely to manage some English than
 * some Korean, and the language picker itself is always in endonyms.
 */
export interface CounterStrings {
  pickLanguage: string;
  pickLanguageHint: string;
  start: string;
  connecting: string;
  waitingStaff: string;
  ended: string;
  typeHere: string;
  send: string;
  holdToSpeak: string;
  listening: string;
  quickPhrases: string;
  confirmNumbers: string;
  rephrase: string;
  fixedPhrase: string;
  checkThis: string;
  translationFailed: string;
  /** Shown on the join screen when nothing can translate at all. */
  translationUnavailable: string;
  emptyConversation: string;
  changeLanguage: string;
  /** Both carry a `{provider}` placeholder, filled in by the caller. */
  sentTo: string;
  mayTrain: string;
}

const EN: CounterStrings = {
  pickLanguage: "Choose your language",
  pickLanguageHint: "Everything you write is translated for the staff member.",
  start: "Start",
  connecting: "Connecting…",
  waitingStaff: "Waiting for the staff member.",
  ended: "This conversation has ended.",
  typeHere: "Type your message",
  send: "Send",
  holdToSpeak: "Hold to speak",
  listening: "Listening…",
  quickPhrases: "Common phrases",
  confirmNumbers: "Confirm the numbers",
  rephrase: "Say it differently",
  fixedPhrase: "Set phrase",
  checkThis: "Please check",
  translationFailed: "Could not translate",
  translationUnavailable: "Translation is not working right now. Please tell the staff member.",
  emptyConversation: "Messages will appear here. Speak or type to begin.",
  changeLanguage: "Change language",
  sentTo: "Translated by {provider}.",
  mayTrain: "On this free tier, {provider} may use what is sent to improve their products.",
};

const STRINGS: Record<string, CounterStrings> = {
  "en-US": EN,
  "ko-KR": {
    pickLanguage: "언어를 선택하세요",
    pickLanguageHint: "작성하신 내용은 담당 직원에게 번역되어 전달됩니다.",
    start: "시작",
    connecting: "연결 중…",
    waitingStaff: "담당 직원을 기다리는 중입니다.",
    ended: "대화가 종료되었습니다.",
    typeHere: "내용을 입력하세요",
    send: "보내기",
    holdToSpeak: "길게 눌러 말하기",
    listening: "듣는 중…",
    quickPhrases: "자주 쓰는 문구",
    confirmNumbers: "숫자 확인",
    rephrase: "다시 표현",
    fixedPhrase: "정형 문구",
    checkThis: "확인 필요",
    translationFailed: "번역하지 못했습니다",
    translationUnavailable: "지금은 번역이 작동하지 않습니다. 담당 직원에게 알려 주세요.",
    emptyConversation: "대화가 여기에 표시됩니다. 말하거나 입력해 시작하세요.",
    changeLanguage: "언어 변경",
    sentTo: "번역은 {provider}에서 처리합니다.",
    mayTrain: "무료 등급에서는 {provider}이(가) 전송된 내용을 서비스 개선에 사용할 수 있습니다.",
  },
  "zh-CN": {
    pickLanguage: "请选择您的语言",
    pickLanguageHint: "您输入的内容会翻译后转达给工作人员。",
    start: "开始",
    connecting: "连接中…",
    waitingStaff: "正在等待工作人员。",
    ended: "对话已结束。",
    typeHere: "请输入内容",
    send: "发送",
    holdToSpeak: "按住说话",
    listening: "正在聆听…",
    quickPhrases: "常用语句",
    confirmNumbers: "确认数字",
    rephrase: "换个说法",
    fixedPhrase: "固定语句",
    checkThis: "请确认",
    translationFailed: "无法翻译",
    translationUnavailable: "目前无法翻译。请告知工作人员。",
    emptyConversation: "消息将显示在这里。说话或输入即可开始。",
    changeLanguage: "更改语言",
    sentTo: "由 {provider} 提供翻译。",
    mayTrain: "在免费方案下，{provider} 可能会使用所发送的内容来改进其产品。",
  },
  "zh-TW": {
    pickLanguage: "請選擇您的語言",
    pickLanguageHint: "您輸入的內容會翻譯後轉達給工作人員。",
    start: "開始",
    connecting: "連線中…",
    waitingStaff: "正在等待工作人員。",
    ended: "對話已結束。",
    typeHere: "請輸入內容",
    send: "傳送",
    holdToSpeak: "按住說話",
    listening: "聆聽中…",
    quickPhrases: "常用語句",
    confirmNumbers: "確認數字",
    rephrase: "換個說法",
    fixedPhrase: "固定語句",
    checkThis: "請確認",
    translationFailed: "無法翻譯",
    translationUnavailable: "目前無法翻譯。請告知工作人員。",
    emptyConversation: "訊息將顯示在這裡。說話或輸入即可開始。",
    changeLanguage: "變更語言",
    sentTo: "由 {provider} 提供翻譯。",
    mayTrain: "在免費方案下，{provider} 可能會使用所傳送的內容來改進其產品。",
  },
  "ja-JP": {
    pickLanguage: "言語を選択してください",
    pickLanguageHint: "入力した内容は翻訳されて担当者に伝わります。",
    start: "開始",
    connecting: "接続中…",
    waitingStaff: "担当者をお待ちください。",
    ended: "この会話は終了しました。",
    typeHere: "メッセージを入力",
    send: "送信",
    holdToSpeak: "長押しで話す",
    listening: "聞き取り中…",
    quickPhrases: "よく使う表現",
    confirmNumbers: "数字を確認",
    rephrase: "言い換える",
    fixedPhrase: "定型文",
    checkThis: "要確認",
    translationFailed: "翻訳できませんでした",
    translationUnavailable: "現在、翻訳が機能していません。担当者にお知らせください。",
    emptyConversation: "メッセージがここに表示されます。話すか入力して始めてください。",
    changeLanguage: "言語を変更",
    sentTo: "翻訳は {provider} が行います。",
    mayTrain: "無料枠では、{provider} が送信内容を製品改善に利用する場合があります。",
  },
  "vi-VN": {
    pickLanguage: "Chọn ngôn ngữ của bạn",
    pickLanguageHint: "Nội dung bạn viết sẽ được dịch cho nhân viên.",
    start: "Bắt đầu",
    connecting: "Đang kết nối…",
    waitingStaff: "Đang chờ nhân viên.",
    ended: "Cuộc trò chuyện đã kết thúc.",
    typeHere: "Nhập nội dung",
    send: "Gửi",
    holdToSpeak: "Giữ để nói",
    listening: "Đang nghe…",
    quickPhrases: "Câu thường dùng",
    confirmNumbers: "Xác nhận số liệu",
    rephrase: "Diễn đạt cách khác",
    fixedPhrase: "Câu mẫu",
    checkThis: "Cần kiểm tra",
    translationFailed: "Không dịch được",
    translationUnavailable: "Hiện không dịch được. Vui lòng báo cho nhân viên.",
    emptyConversation: "Tin nhắn sẽ hiện ở đây. Hãy nói hoặc nhập để bắt đầu.",
    changeLanguage: "Đổi ngôn ngữ",
    sentTo: "Bản dịch do {provider} thực hiện.",
    mayTrain: "Ở gói miễn phí, {provider} có thể dùng nội dung đã gửi để cải thiện sản phẩm.",
  },
  "th-TH": {
    pickLanguage: "เลือกภาษาของคุณ",
    pickLanguageHint: "ข้อความที่คุณพิมพ์จะถูกแปลให้เจ้าหน้าที่",
    start: "เริ่ม",
    connecting: "กำลังเชื่อมต่อ…",
    waitingStaff: "กำลังรอเจ้าหน้าที่",
    ended: "การสนทนาสิ้นสุดแล้ว",
    typeHere: "พิมพ์ข้อความ",
    send: "ส่ง",
    holdToSpeak: "กดค้างเพื่อพูด",
    listening: "กำลังฟัง…",
    quickPhrases: "ประโยคที่ใช้บ่อย",
    confirmNumbers: "ยืนยันตัวเลข",
    rephrase: "พูดใหม่อีกแบบ",
    fixedPhrase: "ประโยคสำเร็จรูป",
    checkThis: "โปรดตรวจสอบ",
    translationFailed: "แปลไม่สำเร็จ",
    translationUnavailable: "ขณะนี้ระบบแปลไม่ทำงาน กรุณาแจ้งเจ้าหน้าที่",
    emptyConversation: "ข้อความจะแสดงที่นี่ พูดหรือพิมพ์เพื่อเริ่ม",
    changeLanguage: "เปลี่ยนภาษา",
    sentTo: "แปลโดย {provider}",
    mayTrain: "ในแพ็กเกจฟรี {provider} อาจนำข้อความที่ส่งไปใช้เพื่อปรับปรุงผลิตภัณฑ์",
  },
  "id-ID": {
    pickLanguage: "Pilih bahasa Anda",
    pickLanguageHint: "Yang Anda tulis akan diterjemahkan untuk petugas.",
    start: "Mulai",
    connecting: "Menghubungkan…",
    waitingStaff: "Menunggu petugas.",
    ended: "Percakapan ini telah berakhir.",
    typeHere: "Ketik pesan Anda",
    send: "Kirim",
    holdToSpeak: "Tahan untuk bicara",
    listening: "Mendengarkan…",
    quickPhrases: "Kalimat umum",
    confirmNumbers: "Konfirmasi angka",
    rephrase: "Ucapkan dengan cara lain",
    fixedPhrase: "Kalimat baku",
    checkThis: "Mohon diperiksa",
    translationFailed: "Tidak dapat menerjemahkan",
    translationUnavailable: "Terjemahan sedang tidak berfungsi. Beri tahu petugas.",
    emptyConversation: "Pesan akan muncul di sini. Bicara atau ketik untuk mulai.",
    changeLanguage: "Ganti bahasa",
    sentTo: "Diterjemahkan oleh {provider}.",
    mayTrain: "Pada paket gratis, {provider} dapat memakai isi yang dikirim untuk meningkatkan produknya.",
  },
  "ru-RU": {
    pickLanguage: "Выберите ваш язык",
    pickLanguageHint: "Всё, что вы напишете, будет переведено для сотрудника.",
    start: "Начать",
    connecting: "Подключение…",
    waitingStaff: "Ожидание сотрудника.",
    ended: "Разговор завершён.",
    typeHere: "Введите сообщение",
    send: "Отправить",
    holdToSpeak: "Удерживайте, чтобы говорить",
    listening: "Слушаю…",
    quickPhrases: "Частые фразы",
    confirmNumbers: "Подтвердить цифры",
    rephrase: "Сказать иначе",
    fixedPhrase: "Готовая фраза",
    checkThis: "Проверьте",
    translationFailed: "Не удалось перевести",
    translationUnavailable: "Сейчас перевод не работает. Сообщите сотруднику.",
    emptyConversation: "Сообщения появятся здесь. Говорите или пишите, чтобы начать.",
    changeLanguage: "Сменить язык",
    sentTo: "Перевод выполняет {provider}.",
    mayTrain: "На бесплатном тарифе {provider} может использовать отправленное для улучшения своих продуктов.",
  },
  "uk-UA": {
    pickLanguage: "Оберіть свою мову",
    pickLanguageHint: "Усе, що ви напишете, буде перекладено для працівника.",
    start: "Почати",
    connecting: "Підключення…",
    waitingStaff: "Очікуємо працівника.",
    ended: "Цю розмову завершено.",
    typeHere: "Введіть повідомлення",
    send: "Надіслати",
    holdToSpeak: "Утримуйте, щоб говорити",
    listening: "Слухаю…",
    quickPhrases: "Поширені фрази",
    confirmNumbers: "Підтвердити числа",
    rephrase: "Сказати інакше",
    fixedPhrase: "Готова фраза",
    checkThis: "Перевірте, будь ласка",
    translationFailed: "Не вдалося перекласти",
    translationUnavailable: "Переклад зараз не працює. Повідомте працівника.",
    emptyConversation: "Повідомлення з’являться тут. Говоріть або введіть текст, щоб почати.",
    changeLanguage: "Змінити мову",
    sentTo: "Переклад виконує {provider}.",
    mayTrain: "На безкоштовному тарифі {provider} може використовувати надіслане для покращення своїх продуктів.",
  },
  "uz-UZ": {
    pickLanguage: "Tilingizni tanlang",
    pickLanguageHint: "Yozganlaringiz xodim uchun tarjima qilinadi.",
    start: "Boshlash",
    connecting: "Ulanmoqda…",
    waitingStaff: "Xodim kutilmoqda.",
    ended: "Suhbat tugadi.",
    typeHere: "Xabaringizni yozing",
    send: "Yuborish",
    holdToSpeak: "Gapirish uchun bosib turing",
    listening: "Tinglanmoqda…",
    quickPhrases: "Ko‘p ishlatiladigan iboralar",
    confirmNumbers: "Raqamlarni tasdiqlang",
    rephrase: "Boshqacha ayting",
    fixedPhrase: "Tayyor ibora",
    checkThis: "Tekshiring",
    translationFailed: "Tarjima qilinmadi",
    translationUnavailable: "Hozir tarjima ishlamayapti. Xodimga xabar bering.",
    emptyConversation: "Xabarlar shu yerda ko‘rinadi. Gapiring yoki yozing.",
    changeLanguage: "Tilni o‘zgartirish",
    sentTo: "Tarjimani {provider} bajaradi.",
    mayTrain: "Bepul tarifda {provider} yuborilgan matndan mahsulotlarini yaxshilash uchun foydalanishi mumkin.",
  },
  "mn-MN": {
    pickLanguage: "Хэлээ сонгоно уу",
    pickLanguageHint: "Таны бичсэн зүйл ажилтанд орчуулагдан очно.",
    start: "Эхлэх",
    connecting: "Холбогдож байна…",
    waitingStaff: "Ажилтныг хүлээж байна.",
    ended: "Яриа дууслаа.",
    typeHere: "Мессежээ бичнэ үү",
    send: "Илгээх",
    holdToSpeak: "Дарж хэлнэ үү",
    listening: "Сонсож байна…",
    quickPhrases: "Түгээмэл хэллэг",
    confirmNumbers: "Тоог баталгаажуулах",
    rephrase: "Өөрөөр хэлэх",
    fixedPhrase: "Бэлэн хэллэг",
    checkThis: "Шалгана уу",
    translationFailed: "Орчуулж чадсангүй",
    translationUnavailable: "Одоогоор орчуулга ажиллахгүй байна. Ажилтанд мэдэгдэнэ үү.",
    emptyConversation: "Мессеж энд харагдана. Ярих эсвэл бичиж эхлээрэй.",
    changeLanguage: "Хэл солих",
    sentTo: "Орчуулгыг {provider} гүйцэтгэнэ.",
    mayTrain: "Үнэгүй багцад {provider} илгээсэн агуулгыг бүтээгдэхүүнээ сайжруулахад ашиглаж болно.",
  },
  "ne-NP": {
    pickLanguage: "आफ्नो भाषा छान्नुहोस्",
    pickLanguageHint: "तपाईंले लेखेको कुरा कर्मचारीका लागि अनुवाद हुन्छ।",
    start: "सुरु",
    connecting: "जडान हुँदै…",
    waitingStaff: "कर्मचारीको प्रतीक्षा गर्दै।",
    ended: "यो कुराकानी समाप्त भयो।",
    typeHere: "आफ्नो सन्देश लेख्नुहोस्",
    send: "पठाउनुहोस्",
    holdToSpeak: "बोल्न थिचिराख्नुहोस्",
    listening: "सुन्दै…",
    quickPhrases: "प्रायः प्रयोग हुने वाक्य",
    confirmNumbers: "अङ्क पुष्टि गर्नुहोस्",
    rephrase: "अर्को तरिकाले भन्नुहोस्",
    fixedPhrase: "तयारी वाक्य",
    checkThis: "जाँच्नुहोस्",
    translationFailed: "अनुवाद गर्न सकिएन",
    translationUnavailable: "अहिले अनुवाद काम गरिरहेको छैन। कृपया कर्मचारीलाई भन्नुहोस्।",
    emptyConversation: "सन्देशहरू यहाँ देखिनेछन्। बोल्नुहोस् वा लेख्नुहोस्।",
    changeLanguage: "भाषा बदल्नुहोस्",
    sentTo: "अनुवाद {provider} ले गर्छ।",
    mayTrain: "निःशुल्क योजनामा {provider} ले पठाइएको सामग्री आफ्ना उत्पादन सुधार गर्न प्रयोग गर्न सक्छ।",
  },
  "es-ES": {
    pickLanguage: "Elija su idioma",
    pickLanguageHint: "Todo lo que escriba se traduce para el personal.",
    start: "Empezar",
    connecting: "Conectando…",
    waitingStaff: "Esperando al personal.",
    ended: "Esta conversación ha terminado.",
    typeHere: "Escriba su mensaje",
    send: "Enviar",
    holdToSpeak: "Mantenga pulsado para hablar",
    listening: "Escuchando…",
    quickPhrases: "Frases habituales",
    confirmNumbers: "Confirmar las cifras",
    rephrase: "Decirlo de otra forma",
    fixedPhrase: "Frase fija",
    checkThis: "Compruébelo",
    translationFailed: "No se pudo traducir",
    translationUnavailable: "Ahora mismo la traducción no funciona. Avise al personal.",
    emptyConversation: "Los mensajes aparecerán aquí. Hable o escriba para empezar.",
    changeLanguage: "Cambiar de idioma",
    sentTo: "Traducido por {provider}.",
    mayTrain: "En el plan gratuito, {provider} puede usar lo enviado para mejorar sus productos.",
  },
  "fr-FR": {
    pickLanguage: "Choisissez votre langue",
    pickLanguageHint: "Ce que vous écrivez est traduit pour l’agent.",
    start: "Commencer",
    connecting: "Connexion…",
    waitingStaff: "En attente de l’agent.",
    ended: "Cette conversation est terminée.",
    typeHere: "Saisissez votre message",
    send: "Envoyer",
    holdToSpeak: "Maintenez pour parler",
    listening: "Écoute…",
    quickPhrases: "Phrases courantes",
    confirmNumbers: "Confirmer les chiffres",
    rephrase: "Dire autrement",
    fixedPhrase: "Phrase type",
    checkThis: "À vérifier",
    translationFailed: "Traduction impossible",
    translationUnavailable: "La traduction ne fonctionne pas pour le moment. Prévenez l’agent.",
    emptyConversation: "Les messages s’afficheront ici. Parlez ou écrivez pour commencer.",
    changeLanguage: "Changer de langue",
    sentTo: "Traduction assurée par {provider}.",
    mayTrain: "Dans l’offre gratuite, {provider} peut utiliser ce qui est envoyé pour améliorer ses produits.",
  },
  "ar-SA": {
    pickLanguage: "اختر لغتك",
    pickLanguageHint: "كل ما تكتبه يُترجم للموظف.",
    start: "ابدأ",
    connecting: "جارٍ الاتصال…",
    waitingStaff: "في انتظار الموظف.",
    ended: "انتهت هذه المحادثة.",
    typeHere: "اكتب رسالتك",
    send: "إرسال",
    holdToSpeak: "اضغط مع الاستمرار للتحدث",
    listening: "يستمع…",
    quickPhrases: "عبارات شائعة",
    confirmNumbers: "تأكيد الأرقام",
    rephrase: "قلها بطريقة أخرى",
    fixedPhrase: "عبارة جاهزة",
    checkThis: "يرجى التحقق",
    translationFailed: "تعذّرت الترجمة",
    translationUnavailable: "الترجمة لا تعمل حالياً. يُرجى إبلاغ الموظف.",
    emptyConversation: "ستظهر الرسائل هنا. تحدّث أو اكتب للبدء.",
    changeLanguage: "تغيير اللغة",
    sentTo: "الترجمة عبر {provider}.",
    mayTrain: "في الباقة المجانية، قد يستخدم {provider} ما يُرسل لتحسين منتجاته.",
  },
  "hi-IN": {
    pickLanguage: "अपनी भाषा चुनें",
    pickLanguageHint: "आप जो लिखेंगे वह कर्मचारी के लिए अनुवादित होगा।",
    start: "शुरू करें",
    connecting: "जुड़ रहा है…",
    waitingStaff: "कर्मचारी की प्रतीक्षा है।",
    ended: "यह बातचीत समाप्त हो गई।",
    typeHere: "अपना संदेश लिखें",
    send: "भेजें",
    holdToSpeak: "बोलने के लिए दबाए रखें",
    listening: "सुन रहा है…",
    quickPhrases: "आम वाक्य",
    confirmNumbers: "अंक सत्यापित करें",
    rephrase: "दूसरे ढंग से कहें",
    fixedPhrase: "तयशुदा वाक्य",
    checkThis: "जाँच लें",
    translationFailed: "अनुवाद नहीं हो सका",
    translationUnavailable: "अभी अनुवाद काम नहीं कर रहा है। कृपया कर्मचारी को बताएं।",
    emptyConversation: "संदेश यहाँ दिखेंगे। बोलें या लिखें।",
    changeLanguage: "भाषा बदलें",
    sentTo: "अनुवाद {provider} द्वारा।",
    mayTrain: "निःशुल्क योजना में {provider} भेजी गई सामग्री का उपयोग अपने उत्पाद सुधारने के लिए कर सकता है।",
  },
  "tr-TR": {
    pickLanguage: "Dilinizi seçin",
    pickLanguageHint: "Yazdığınız her şey görevli için çevrilir.",
    start: "Başla",
    connecting: "Bağlanıyor…",
    waitingStaff: "Görevli bekleniyor.",
    ended: "Bu görüşme sona erdi.",
    typeHere: "Mesajınızı yazın",
    send: "Gönder",
    holdToSpeak: "Konuşmak için basılı tutun",
    listening: "Dinliyor…",
    quickPhrases: "Sık kullanılan ifadeler",
    confirmNumbers: "Sayıları doğrula",
    rephrase: "Başka türlü söyle",
    fixedPhrase: "Hazır ifade",
    checkThis: "Lütfen kontrol edin",
    translationFailed: "Çevrilemedi",
    translationUnavailable: "Çeviri şu anda çalışmıyor. Lütfen görevliye bildirin.",
    emptyConversation: "Mesajlar burada görünecek. Konuşun ya da yazın.",
    changeLanguage: "Dili değiştir",
    sentTo: "Çeviriyi {provider} yapıyor.",
    mayTrain: "Ücretsiz pakette {provider}, gönderilenleri ürünlerini geliştirmek için kullanabilir.",
  },
  "de-DE": {
    pickLanguage: "Wählen Sie Ihre Sprache",
    pickLanguageHint: "Alles, was Sie schreiben, wird für den Mitarbeiter übersetzt.",
    start: "Starten",
    connecting: "Verbinden…",
    waitingStaff: "Warten auf den Mitarbeiter.",
    ended: "Dieses Gespräch ist beendet.",
    typeHere: "Nachricht eingeben",
    send: "Senden",
    holdToSpeak: "Zum Sprechen gedrückt halten",
    listening: "Hört zu…",
    quickPhrases: "Häufige Sätze",
    confirmNumbers: "Zahlen bestätigen",
    rephrase: "Anders sagen",
    fixedPhrase: "Feste Formulierung",
    checkThis: "Bitte prüfen",
    translationFailed: "Konnte nicht übersetzt werden",
    translationUnavailable: "Die Übersetzung funktioniert gerade nicht. Bitte sagen Sie dem Mitarbeiter Bescheid.",
    emptyConversation: "Nachrichten erscheinen hier. Sprechen oder schreiben Sie, um zu beginnen.",
    changeLanguage: "Sprache ändern",
    sentTo: "Übersetzt von {provider}.",
    mayTrain: "Im kostenlosen Tarif darf {provider} das Gesendete zur Produktverbesserung verwenden.",
  },
  "pt-BR": {
    pickLanguage: "Escolha o seu idioma",
    pickLanguageHint: "Tudo o que você escrever é traduzido para o atendente.",
    start: "Começar",
    connecting: "Conectando…",
    waitingStaff: "Aguardando o atendente.",
    ended: "Esta conversa foi encerrada.",
    typeHere: "Digite a sua mensagem",
    send: "Enviar",
    holdToSpeak: "Mantenha pressionado para falar",
    listening: "Ouvindo…",
    quickPhrases: "Frases comuns",
    confirmNumbers: "Confirmar os números",
    rephrase: "Dizer de outro jeito",
    fixedPhrase: "Frase pronta",
    checkThis: "Por favor, verifique",
    translationFailed: "Não foi possível traduzir",
    translationUnavailable: "A tradução não está funcionando agora. Avise o atendente, por favor.",
    emptyConversation: "As mensagens aparecem aqui. Fale ou digite para começar.",
    changeLanguage: "Mudar de idioma",
    sentTo: "Traduzido por {provider}.",
    mayTrain: "No plano gratuito, a {provider} pode usar o que é enviado para melhorar seus produtos.",
  },
  "tl-PH": {
    pickLanguage: "Piliin ang iyong wika",
    pickLanguageHint: "Ang lahat ng isusulat mo ay isasalin para sa staff.",
    start: "Simulan",
    connecting: "Kumokonekta…",
    waitingStaff: "Hinihintay ang staff.",
    ended: "Tapos na ang usapang ito.",
    typeHere: "I-type ang iyong mensahe",
    send: "Ipadala",
    holdToSpeak: "Pindutin nang matagal para magsalita",
    listening: "Nakikinig…",
    quickPhrases: "Mga karaniwang pahayag",
    confirmNumbers: "Kumpirmahin ang mga numero",
    rephrase: "Sabihin sa ibang paraan",
    fixedPhrase: "Handang pahayag",
    checkThis: "Pakisuri",
    translationFailed: "Hindi naisalin",
    translationUnavailable: "Hindi gumagana ang pagsasalin ngayon. Pakisabi sa staff.",
    emptyConversation: "Lalabas dito ang mga mensahe. Magsalita o mag-type para magsimula.",
    changeLanguage: "Palitan ang wika",
    sentTo: "Isinalin ng {provider}.",
    mayTrain: "Sa libreng tier, maaaring gamitin ng {provider} ang ipinapadala para pagbutihin ang kanilang produkto.",
  },
  "bn-BD": {
    pickLanguage: "আপনার ভাষা বেছে নিন",
    pickLanguageHint: "আপনি যা লিখবেন তা কর্মীর জন্য অনুবাদ করা হবে।",
    start: "শুরু করুন",
    connecting: "সংযোগ করা হচ্ছে…",
    waitingStaff: "কর্মীর জন্য অপেক্ষা করা হচ্ছে।",
    ended: "এই কথোপকথন শেষ হয়েছে।",
    typeHere: "আপনার বার্তা লিখুন",
    send: "পাঠান",
    holdToSpeak: "কথা বলতে চেপে ধরুন",
    listening: "শোনা হচ্ছে…",
    quickPhrases: "প্রচলিত বাক্য",
    confirmNumbers: "সংখ্যাগুলো নিশ্চিত করুন",
    rephrase: "অন্যভাবে বলুন",
    fixedPhrase: "নির্ধারিত বাক্য",
    checkThis: "অনুগ্রহ করে দেখে নিন",
    translationFailed: "অনুবাদ করা যায়নি",
    translationUnavailable: "এখন অনুবাদ কাজ করছে না। অনুগ্রহ করে কর্মীকে জানান।",
    emptyConversation: "বার্তা এখানে দেখা যাবে। শুরু করতে বলুন বা লিখুন।",
    changeLanguage: "ভাষা পরিবর্তন করুন",
    sentTo: "{provider} অনুবাদ করেছে।",
    mayTrain: "ফ্রি টিয়ারে {provider} পাঠানো বিষয়বস্তু তাদের পণ্য উন্নত করতে ব্যবহার করতে পারে।",
  },
  "ur-PK": {
    pickLanguage: "اپنی زبان منتخب کریں",
    pickLanguageHint: "آپ جو کچھ لکھیں گے وہ عملے کے لیے ترجمہ ہو جائے گا۔",
    start: "شروع کریں",
    connecting: "جوڑا جا رہا ہے…",
    waitingStaff: "عملے کا انتظار ہے۔",
    ended: "یہ گفتگو ختم ہو چکی ہے۔",
    typeHere: "اپنا پیغام لکھیں",
    send: "بھیجیں",
    holdToSpeak: "بولنے کے لیے دبائے رکھیں",
    listening: "سن رہا ہے…",
    quickPhrases: "عام جملے",
    confirmNumbers: "اعداد کی تصدیق کریں",
    rephrase: "دوسرے الفاظ میں کہیں",
    fixedPhrase: "طے شدہ جملہ",
    checkThis: "براہ کرم جانچ لیں",
    translationFailed: "ترجمہ نہیں ہو سکا",
    translationUnavailable: "ترجمہ اس وقت کام نہیں کر رہا۔ براہ کرم عملے کو بتائیں۔",
    emptyConversation: "پیغامات یہاں دکھائی دیں گے۔ شروع کرنے کے لیے بولیں یا لکھیں۔",
    changeLanguage: "زبان تبدیل کریں",
    sentTo: "{provider} نے ترجمہ کیا۔",
    mayTrain: "مفت درجے میں {provider} بھیجی گئی معلومات اپنی مصنوعات بہتر بنانے کے لیے استعمال کر سکتا ہے۔",
  },
  "km-KH": {
    pickLanguage: "សូមជ្រើសរើសភាសារបស់អ្នក",
    pickLanguageHint: "អ្វីដែលអ្នកសរសេរនឹងត្រូវបកប្រែជូនបុគ្គលិក។",
    start: "ចាប់ផ្តើម",
    connecting: "កំពុងភ្ជាប់…",
    waitingStaff: "កំពុងរង់ចាំបុគ្គលិក។",
    ended: "ការសន្ទនានេះបានបញ្ចប់ហើយ។",
    typeHere: "សូមវាយសាររបស់អ្នក",
    send: "ផ្ញើ",
    holdToSpeak: "ចុចឱ្យជាប់ដើម្បីនិយាយ",
    listening: "កំពុងស្តាប់…",
    quickPhrases: "ឃ្លាប្រើញឹកញាប់",
    confirmNumbers: "បញ្ជាក់លេខ",
    rephrase: "និយាយបែបផ្សេង",
    fixedPhrase: "ឃ្លាកំណត់",
    checkThis: "សូមពិនិត្យ",
    translationFailed: "មិនអាចបកប្រែបាន",
    translationUnavailable: "ការបកប្រែមិនដំណើរការឥឡូវនេះទេ។ សូមប្រាប់បុគ្គលិក។",
    emptyConversation: "សារនឹងបង្ហាញនៅទីនេះ។ សូមនិយាយ ឬវាយបញ្ចូលដើម្បីចាប់ផ្តើម។",
    changeLanguage: "ប្តូរភាសា",
    sentTo: "បកប្រែដោយ {provider}។",
    mayTrain: "នៅកម្រិតឥតគិតថ្លៃ {provider} អាចប្រើអ្វីដែលបានផ្ញើដើម្បីកែលម្អផលិតផលរបស់ខ្លួន។",
  },
  "my-MM": {
    pickLanguage: "သင့်ဘာသာစကားကို ရွေးပါ",
    pickLanguageHint: "သင်ရေးသမျှကို ဝန်ထမ်းအတွက် ဘာသာပြန်ပေးပါမည်။",
    start: "စတင်ရန်",
    connecting: "ချိတ်ဆက်နေသည်…",
    waitingStaff: "ဝန်ထမ်းကို စောင့်ဆိုင်းနေသည်။",
    ended: "ဤစကားဝိုင်း ပြီးဆုံးသွားပါပြီ။",
    typeHere: "သင့်စာကို ရိုက်ထည့်ပါ",
    send: "ပို့ရန်",
    holdToSpeak: "စကားပြောရန် ဖိထားပါ",
    listening: "နားထောင်နေသည်…",
    quickPhrases: "အသုံးများသော စကားစုများ",
    confirmNumbers: "ဂဏန်းများကို အတည်ပြုရန်",
    rephrase: "တခြားနည်းနဲ့ ပြောရန်",
    fixedPhrase: "သတ်မှတ်စကားစု",
    checkThis: "ကျေးဇူးပြု၍ စစ်ဆေးပါ",
    translationFailed: "ဘာသာမပြန်နိုင်ပါ",
    translationUnavailable: "ဘာသာပြန်ခြင်း ယခုအလုပ်မလုပ်ပါ။ ဝန်ထမ်းကို အသိပေးပါ။",
    emptyConversation: "စာများ ဤနေရာတွင် ပေါ်လာမည်။ စတင်ရန် ပြောပါ သို့မဟုတ် ရိုက်ထည့်ပါ။",
    changeLanguage: "ဘာသာစကား ပြောင်းရန်",
    sentTo: "{provider} က ဘာသာပြန်သည်။",
    mayTrain: "အခမဲ့အဆင့်တွင် {provider} သည် ပို့လိုက်သည့်အရာကို ၎င်းတို့၏ ထုတ်ကုန်တိုးတက်စေရန် အသုံးပြုနိုင်သည်။",
  },
  // Uyghur. Interface controls only. The administrative terminology this
  // product must not invent is handled by the glossary layer, which keeps the
  // Latin code visible rather than inventing an Uyghur equivalent for it.
  "ug-CN": {
    pickLanguage: "تىلىڭىزنى تاللاڭ",
    pickLanguageHint: "سىز يازغان مەزمۇن خىزمەتچىگە تەرجىمە قىلىنىدۇ.",
    start: "باشلاش",
    connecting: "ئۇلىنىۋاتىدۇ…",
    waitingStaff: "خىزمەتچى كۈتۈلمەكتە.",
    ended: "بۇ سۆزلىشىش ئاخىرلاشتى.",
    typeHere: "ئۇچۇرىڭىزنى كىرگۈزۈڭ",
    send: "ئەۋەتىش",
    holdToSpeak: "سۆزلەش ئۈچۈن بېسىپ تۇرۇڭ",
    listening: "ئاڭلاۋاتىدۇ…",
    quickPhrases: "كۆپ ئىشلىتىلىدىغان جۈملىلەر",
    confirmNumbers: "ساننى جەزملەشتۈرۈڭ",
    rephrase: "باشقىچە ئېيتىڭ",
    fixedPhrase: "بەلگىلەنگەن جۈملە",
    checkThis: "تەكشۈرۈپ بېقىڭ",
    translationFailed: "تەرجىمە قىلغىلى بولمىدى",
    translationUnavailable: "تەرجىمە ھازىر ئىشلىمەيۋاتىدۇ. خىزمەتچىگە ئېيتىڭ.",
    emptyConversation: "ئۇچۇرلار بۇ يەردە كۆرۈنىدۇ. باشلاش ئۈچۈن سۆزلەڭ ياكى كىرگۈزۈڭ.",
    changeLanguage: "تىلنى ئۆزگەرتىش",
    sentTo: "{provider} تەرجىمە قىلدى.",
    mayTrain: "ھەقسىز قاتلامدا {provider} ئەۋەتىلگەن مەزمۇننى مەھسۇلاتىنى ياخشىلاشقا ئىشلىتىشى مۇمكىن.",
  },
};

/** Strings for a language tag, falling back to the base tag and then English. */
export function stringsFor(code: string): CounterStrings {
  const exact = STRINGS[code];
  if (exact) return exact;
  const base = code.split("-")[0].toLowerCase();
  for (const [key, value] of Object.entries(STRINGS)) {
    if (key.split("-")[0].toLowerCase() === base) return value;
  }
  return EN;
}

/** Share of the interface a visitor sees in their own language. Diagnostics. */
export const hasStrings = (code: string): boolean =>
  Object.keys(STRINGS).some(
    (key) => key === code || key.split("-")[0] === code.split("-")[0].toLowerCase(),
  );

export interface CounterActionStrings {
  simplify: string;
  retry: string;
  integrityWarning: string;
  lowConfidence: string;
}

const ACTION_EN: CounterActionStrings = {
  simplify: "Make simpler",
  retry: "Translate again",
  integrityWarning: "An important value may not match the original. Please check it.",
  lowConfidence: "Some wording is uncertain. Please check it.",
};

const ACTION_STRINGS: Record<string, CounterActionStrings> = {
  en: ACTION_EN,
  ko: {
    simplify: "더 쉽게",
    retry: "다시 번역",
    integrityWarning: "중요한 값이 원문과 다를 수 있어요. 다시 확인해 주세요.",
    lowConfidence: "일부 내용이 불확실해요. 다시 확인해 주세요.",
  },
  zh: {
    simplify: "说得更简单",
    retry: "重新翻译",
    integrityWarning: "重要信息可能与原文不一致，请核对。",
    lowConfidence: "部分内容不确定，请核对。",
  },
  ja: {
    simplify: "もっと簡単に",
    retry: "もう一度翻訳",
    integrityWarning: "重要な値が原文と一致しない可能性があります。確認してください。",
    lowConfidence: "一部の内容が不確かです。確認してください。",
  },
  vi: {
    simplify: "Nói đơn giản hơn",
    retry: "Dịch lại",
    integrityWarning: "Một thông tin quan trọng có thể không khớp bản gốc. Hãy kiểm tra.",
    lowConfidence: "Một số nội dung chưa chắc chắn. Hãy kiểm tra.",
  },
  th: {
    simplify: "ให้ง่ายขึ้น",
    retry: "แปลอีกครั้ง",
    integrityWarning: "ข้อมูลสำคัญอาจไม่ตรงกับต้นฉบับ กรุณาตรวจสอบ",
    lowConfidence: "เนื้อหาบางส่วนไม่แน่นอน กรุณาตรวจสอบ",
  },
  id: {
    simplify: "Buat lebih sederhana",
    retry: "Terjemahkan lagi",
    integrityWarning: "Nilai penting mungkin tidak sama dengan teks asli. Harap periksa.",
    lowConfidence: "Sebagian isi belum pasti. Harap periksa.",
  },
  ru: {
    simplify: "Сказать проще",
    retry: "Перевести снова",
    integrityWarning: "Важное значение может не совпадать с оригиналом. Проверьте его.",
    lowConfidence: "Часть текста неоднозначна. Проверьте её.",
  },
  uk: {
    simplify: "Сказати простіше",
    retry: "Перекласти ще раз",
    integrityWarning: "Важливе значення може не збігатися з оригіналом. Перевірте його.",
    lowConfidence: "Деякі формулювання можуть бути неточними. Перевірте їх.",
  },
  ar: {
    simplify: "تبسيط العبارة",
    retry: "إعادة الترجمة",
    integrityWarning: "قد لا تتطابق معلومة مهمة مع الأصل. يرجى التحقق منها.",
    lowConfidence: "بعض المحتوى غير مؤكد. يرجى التحقق منه.",
  },
  ur: {
    simplify: "آسان بنائیں",
    retry: "دوبارہ ترجمہ کریں",
    integrityWarning: "کوئی اہم معلومات اصل سے مختلف ہو سکتی ہے۔ براہ کرم جانچ لیں۔",
    lowConfidence: "کچھ مواد غیر یقینی ہے۔ براہ کرم جانچ لیں۔",
  },
  ug: {
    simplify: "ئاددىيلاشتۇرۇش",
    retry: "قايتا تەرجىمە قىلىش",
    integrityWarning: "مۇھىم ئۇچۇر ئەسلى تېكىستكە ماس كەلمەسلىكى مۇمكىن. تەكشۈرۈپ بېقىڭ.",
    lowConfidence: "بەزى مەزمۇن ئېنىق ئەمەس. تەكشۈرۈپ بېقىڭ.",
  },
  tr: {
    simplify: "Daha basit söyle",
    retry: "Yeniden çevir",
    integrityWarning: "Önemli bir bilgi özgün metinle uyuşmayabilir. Lütfen kontrol edin.",
    lowConfidence: "Bazı ifadeler belirsiz. Lütfen kontrol edin.",
  },
  de: {
    simplify: "Einfacher sagen",
    retry: "Erneut übersetzen",
    integrityWarning: "Ein wichtiger Wert stimmt möglicherweise nicht mit dem Original überein. Bitte prüfen.",
    lowConfidence: "Einige Formulierungen sind unsicher. Bitte prüfen.",
  },
  pt: {
    simplify: "Dizer mais simples",
    retry: "Traduzir de novo",
    integrityWarning: "Um valor importante pode não corresponder ao original. Por favor, verifique.",
    lowConfidence: "Parte do conteúdo é incerta. Por favor, verifique.",
  },
  fr: {
    simplify: "Dire plus simplement",
    retry: "Traduire à nouveau",
    integrityWarning: "Une information importante peut ne pas correspondre à l’original. Veuillez vérifier.",
    lowConfidence: "Certains éléments sont incertains. Veuillez vérifier.",
  },
  es: {
    simplify: "Decirlo más simple",
    retry: "Traducir de nuevo",
    integrityWarning: "Un dato importante puede no coincidir con el original. Por favor, verifíquelo.",
    lowConfidence: "Parte del contenido es incierto. Por favor, verifíquelo.",
  },
};

export function actionStringsFor(code: string): CounterActionStrings {
  return ACTION_STRINGS[code.split("-")[0].toLowerCase()] ?? ACTION_EN;
}
